
@extends('layouts.lay')  <!-- Assuming you have a layout file -->

@section('content')

    @include('layouts.navbar')


   <div class="container">
   <div class="container drill-main d-flex  justify-content-center mt-5">
        <div class="row ">
            <div class="col">
            <h1>Advance Systems</h1>
            <p>To ensure optimal performance from the drills, maintaining proper contact between the bits and the rock is crucial, especially when the piston transmits energy through impact. In manual drilling, small equipment requires a drill bit oscillating between 3 and 5 kN, while large drills need more than 15 kN for effective operation.</p>
          
            <a class="text-dark fw-bold pop-up"href="#"><h3>Airlegs  </h3></a>
            
            <p>- An airleg comprises two tubes, an outer lightweight metal tube, and an inner steel tube connected to the jackhammer. The inner tube, acting as a piston with a valve, is linked to compressed air.</p>
           <a class="text-dark fw-bold pop-up1"href="#"> <h3>Chain feeds </h3></a>
           
            <p>-  This system involves a heavy chain running between two channels, powered by a pneumatic or hydraulic piston motor through a worm and wheel gearbox.</p>
            <h3>Screwfeeds </h3>
            <p>- Feed thrust is generated by a lead screw's rotation driven by a piston or gear air motor. The screw, with a small diameter relative to its length, is susceptible to bending forces and vibrations during drilling.</p>
            <h3>Cablefeed </h3>
            <p>- Popular in Canada and mounted on specialized jumbos called Stopewagons, this system consists of a hollow extrusion where the drilling machine slides. </p>
            <a class="text-dark fw-bold pop-up2" href="#">  <h3>Hydraulic feeds </h3></a>
            <p>- This system utilizes a hydraulic cylinder to move the drill along the support boom efficiently.</p>
         </div>
     </div>
      <div class=" mb-3 mt-5 btn d-flex justify-content-end outline-none  border-0">
        <a class="text-decoration-none text-dark " href="{{ route('drill8') }}"><button type="button" class="rock-btn shadow-lg pl-5 pr-5">Back</button> </a>
        <a class="text-decoration-none text-dark " href="{{ route('drill10') }}"><button type="button" class="rock-btn shadow-lg pl-5 pr-5 ml-3">Next</button> </a>
      
        
      </div>
</div>
   </div>
  




   <!-- Modal1 -->

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Introduction</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                <img src="{{ asset('img/airleg.png') }}"alt="">
                <p>Cross section of a pneumatic airleg (Padley and Venables)</p>
                
        </div>

         <div class="modal-footer">
            <button type="button" class="btn btn-secondary close1" data-dismiss="modal">Close</button>
      
         </div>
      </div>
   </div>
</div>
<!-- Modal2 -->
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Introduction</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                <img src="{{ asset('img/chain.png') }}"alt="">
                <p>Chain feed (Padley and Venables)</p>
                

         <div class="modal-footer">
            <button type="button" class="btn btn-secondary close1" data-dismiss="modal">Close</button>
      
         </div>
      </div>
   </div>
</div>
<!-- Modal3 -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Introduction</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                <img src="{{ asset('img/hydraulic.png') }}"alt="">
                <p>Hydraulic drifter feed</p>
                

         <div class="modal-footer">
            <button type="button" class="btn btn-secondary close1" data-dismiss="modal">Close</button>
      
         </div>
      </div>
   </div>
</div>
<!-- JavaScript to trigger the modal automatically and close it on button click -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
   $(document).ready(function(){
      
       // Close modal on button click
       $('.close').on('click', function() {
           window.speechSynthesis.cancel(); // Stop text-to-speech
           $('#exampleModal').modal('hide');
       });
       $('.close1').on('click', function() {
           window.speechSynthesis.cancel(); // Stop text-to-speech
           $('#exampleModal').modal('hide');
       });
       
       $('.close').on('click', function() {
           window.speechSynthesis.cancel(); // Stop text-to-speech
           $('#exampleModal1').modal('hide');
       });
       $('.close1').on('click', function() {
           window.speechSynthesis.cancel(); // Stop text-to-speech
           $('#exampleModal1').modal('hide');
       });
       $('.close').on('click', function() {
           window.speechSynthesis.cancel(); // Stop text-to-speech
           $('#exampleModal2').modal('hide');
       });
       $('.close1').on('click', function() {
           window.speechSynthesis.cancel(); // Stop text-to-speech
           $('#exampleModal2').modal('hide');
       });



       // Open modal when pop-up is clicked
       $('.pop-up').on('click', function() {
           $('#exampleModal').modal('show');
       });

       $('.pop-up1').on('click', function() {
           $('#exampleModal1').modal('show');
       });
       $('.pop-up2').on('click', function() {
           $('#exampleModal1').modal('show');
       });
   });
</script>

@endsection
